# .github/dependabot.yml
version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    open-pull-requests-limit: 3
    labels:
      - "github_actions"
    schedule:
      interval: "weekly"
      day: friday
      time: '04:00'

  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 3
    labels:
      - "docker"
    schedule:
      interval: "weekly"
      day: friday
      time: '04:10'

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 3
    labels:
      - "pip"
    schedule:
      interval: "weekly"
      day: friday
      time: '04:20'
